USE MASTER

CREATE DATABASE [DBFG]
ON PRIMARY
(
	NAME ='DBFG',
	FILENAME ='C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\DBFG.mdf',
	SIZE =4096KB,FILEGROWTH =1024KB
),
(
NAME ='DBFG_1',
	FILENAME ='C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\DBFG_1.M=ndf',
	SIZE =4096KB, FILEGROWTH =1024KB
)

LOG ON(
	NAME ='DBFG_log',
	FILENAME ='C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\DBFG_log.ldf',
	SIZE =1024kb,FILEGROWTH =10%
)


SELECT * FROM SYS.filegroups

ALTER DATABASE [DBFG] ADD FILEGROUP [SDBFG]


ALTER DATABASE [DBFG] 
ADD FILE
(
    NAME ='DBFG_TEST',
	FILENAME ='C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\DBFG_TEST.Ndf',
	SIZE =1024kb,FILEGROWTH =10%
) 
TO FILEGROUP [SDBFG]


select * from sys.database_files




